

services:

  api:
    container_name: vr_tech
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - default


  redis:
    image: redis:7-alpine
    container_name: redis_broker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - default



  db:
    container_name: test_postgres
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data


  celery:
    container_name: test_celery
    build:
      context: .
      dockerfile: celery_app/Dockerfile
    depends_on:
      - api
      - db
      - redis
    env_file:
      - .env
    networks:
      - default


volumes:
  postgres_data:
  redis_data:

networks:
  default:
    driver: bridge