"""empty message

Revision ID: 10e2e462ef48
Revises: 
Create Date: 2025-10-05 19:15:33.288789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e2e462ef48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.String(), nullable=False))
    op.create_index(op.f('ix_product_description'), 'product', ['description'], unique=False)
    op.create_foreign_key(None, 'product_history', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_history', type_='foreignkey')
    op.drop_index(op.f('ix_product_description'), table_name='product')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
