"""offers_table

Revision ID: 25568e20013a
Revises: 7a7757b0497f
Create Date: 2025-10-05 19:37:33.452949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25568e20013a'
down_revision: Union[str, Sequence[str], None] = '7a7757b0497f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('offer', sa.Column('seller', sa.String(), nullable=False))
    op.add_column('offer', sa.Column('price', sa.Numeric(scale=2), nullable=False))
    op.create_foreign_key(None, 'offer', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='foreignkey')
    op.drop_column('offer', 'price')
    op.drop_column('offer', 'seller')
    op.drop_column('offer', 'product_id')
    # ### end Alembic commands ###
