"""add_constrains

Revision ID: 7a7757b0497f
Revises: 10e2e462ef48
Create Date: 2025-10-05 19:24:56.330507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7757b0497f'
down_revision: Union[str, Sequence[str], None] = '10e2e462ef48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_product_full_duplicate', 'product', ['name', 'description', 'category', 'min_price', 'max_price', 'rate', 'review_amount', 'seller_amount', 'image_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_full_duplicate', 'product', type_='unique')
    # ### end Alembic commands ###
